### ISSUE TITLE
spawn not defined error

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#241]
Just got newest code and I get the following error every 10 to 50 ticks or so.

ReferenceError: spawn is not defined
    at probeSpawn (population:226:55)
    at arrayEach (/opt/engine/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3345:13)
    at Object.loop (population:227:15)
    at Object.module.exports.loop (main:14:16)
    at __mainLoop:1:52

**Comment by cyberblast** [comment]
Yup, sorry. Hope that's better now. Can't check it right now...

**Comment by Dasku** [comment]
Fixed, thanks a lot.
